services:
  postgres:
    image: postgres:latest
    container_name: postgres_fastapi
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi
    ports:
      - 5432:5432
    restart: always
